CREATE TABLE user_events (
  id SERIAL PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  queue_id integer REFERENCES queues(id) ON DELETE CASCADE NOT NULL,
  time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  help BOOLEAN NOT NULL DEFAULT 'f',
  left_queue BOOLEAN NOT NULL DEFAULT 'f',
  queue_length INTEGER NOT NULL,
  help_amount INTEGER NOT NULL,
  present_amount INTEGER NOT NULL
)
